use_frameworks!

platform :ios, '9.0'

target 'JRXFoundationTest_Example' do
  pod 'JRXFoundationTest', :path => '../'

  target 'JRXFoundationTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
